language: ruby
before_script:
  - sh -e /etc/init.d/xvfb start
  - export DISPLAY=:99.0
script:
  - bundle exec rake
notifications:
  email:
    - diego.domingues16@gmail.com
rvm:
  - 2.1.5
addons:
  code_climate:
    repo_token: 94cd0b0ff03ee6eb48b3f115a84ee3432cfbf594064a38fa1c5e7946c669d38b